# Generated by Django 3.1.14 on 2022-08-16 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('MARKETING', 'MARKETING'), ('ENGINEERING', 'ENGINEERING'), ('GROWTH', 'GROWTH'), ('PRODUCT', 'PRODUCT')], max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
